
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 19 13:24:11 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCREMENT = 35;
  public static final int CONST = 18;
  public static final int GE = 45;
  public static final int NUMCONST = 14;
  public static final int CASE = 28;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 31;
  public static final int DECREMENT = 36;
  public static final int MINUS = 33;
  public static final int RPAREN = 7;
  public static final int AND = 39;
  public static final int LT = 46;
  public static final int OR = 38;
  public static final int QMARK = 40;
  public static final int COMMA = 8;
  public static final int CLASS = 19;
  public static final int DIV = 51;
  public static final int PLUS = 11;
  public static final int IF = 23;
  public static final int LE = 47;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 34;
  public static final int error = 1;
  public static final int MUL = 50;
  public static final int PND = 48;
  public static final int MOD = 52;
  public static final int BREAK = 30;
  public static final int IDENT = 15;
  public static final int VOID = 13;
  public static final int SWITCH = 27;
  public static final int SAME = 42;
  public static final int COLON = 29;
  public static final int LBRACE = 3;
  public static final int ELSE = 24;
  public static final int LSQUARE = 21;
  public static final int ENUM = 41;
  public static final int READ = 32;
  public static final int RSQUARE = 22;
  public static final int CHARCONST = 16;
  public static final int WHILE = 26;
  public static final int RBRACE = 4;
  public static final int FULLSTOP = 37;
  public static final int BOOLCONST = 17;
  public static final int EXTENDS = 20;
  public static final int PROG = 2;
  public static final int DIFF = 43;
  public static final int AT = 49;
  public static final int GT = 44;
  public static final int PRINT = 9;
  public static final int DO = 25;
}

